CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch \
    --master_port=${MASTER_PORT:-$RANDOM} \
    --nproc_per_node=2 hier/train.py \
    --lr 1e-4 --epochs 100 --batch_size 90 \
    --num_hproxies 512 --clip_r 2.3 \
    --hyp_c 0.1 --warmup_epochs 1 \
    --weight_decay 1e-2 --use_fp16 True \
    --clip_grad 1.0 --eval_freq 1 \
    --lambda1 1 --lambda2 0.5 --topk 20 --mrg 0.1 \
    --dataset Cars --model resnet50 \
    --IPC 2 --loss PA --emb 512 --bn_freeze True --use_lastnorm True \
    --optimizer adamw --lr_decay 10 --lr_decay_gamma 0.5