CUDA_VISIBLE_DEVICES=2,3 python -m torch.distributed.launch \
    --master_port=${MASTER_PORT:-$RANDOM} \
    --nproc_per_node=2 hier/train.py \
    --lr 1e-5 --epochs 150 --batch_size 90 \
    --num_hproxies 512 --clip_r 2.3 \
    --hyp_c 0.1 --warmup_epochs 5 \
    --weight_decay 1e-4 --use_fp16 True \
    --clip_grad 1.0 --eval_freq 1 \
    --lambda1 1 --lambda2 0.5 --topk 20 --mrg 0.1 \
    --dataset Inshop --model vit_small_patch16_224 \
    --IPC 2 --loss PA --emb 512 --use_lastnorm True \
    --optimizer adamw --fc_lr_scale 1e2